//
//  SampleDate.swift
//  Link's Recipes
//
//  Created by Martin List on 14/03/2017.
//  Copyright © 2017 Martin List. All rights reserved.
//

import Foundation

let foodData = [
    Food(name:"Baked Apple", hearts: 0.75,
         ingredientNames: Ingredients(firstIngredient: "Apple")),
    Food(name:"Baked Palm Fruit", hearts: 1.5,
         ingredientNames: Ingredients(firstIngredient: "Palm Fruit")),
    Food(name:"Baked Fortified Pumpkin", hearts: 0.75,
         ingredientNames: Ingredients(firstIngredient: "Fortified Pumpkin")),
    Food(name:"Blueshell Escargot", hearts: 4.5,
         ingredientNames: Ingredients(firstIngredient: "Hearty Blueshell Snail")),
    Food(name:"Campfire Egg", hearts: 1.5,
         ingredientNames: Ingredients(firstIngredient: "Bird Egg")),
    Food(name:"Charred Pepper", hearts: 0.75,
         ingredientNames: Ingredients(firstIngredient: "Spicy Pepper")),
    Food(name:"Roasted Armoranth", hearts: 0.5,
         ingredientNames: Ingredients(firstIngredient: "Armoranth")),
    Food(name:"Roasted Hearty Bass", hearts: 3.0,
         ingredientNames: Ingredients(firstIngredient: "Hearty Bass")),
    Food(name:"Roasted Big Radish", hearts: 6.0,
         ingredientNames: Ingredients(firstIngredient: "Big Radish")),
    Food(name:"Roasted Bird Thigh", hearts: 2.25,
         ingredientNames: Ingredients(firstIngredient: "Raw Bird Thigh")),
    Food(name:"Roasted Carp", hearts: 1.5,
         ingredientNames: Ingredients(firstIngredient: "Any Carp")),
    Food(name:"Roasted Hearty Durian", hearts: 4.5,
         ingredientNames: Ingredients(firstIngredient: "Hearty Durian")),
    Food(name:"Roasted Endura Carrot", hearts: 3.0,
         ingredientNames: Ingredients(firstIngredient: "Endura Carrot")),
    Food(name:"Roasted Hydromelon", hearts: 0.75,
         ingredientNames: Ingredients(firstIngredient: "Hydromelon")),
    Food(name:"Roasted Lotus Seeds", hearts: 0.75,
         ingredientNames: Ingredients(firstIngredient: "Fleet-Lotus Seeds")),
    Food(name:"Roasted Mighty Bananas", hearts: 0.75,
         ingredientNames: Ingredients(firstIngredient: "Mighty Bananas")),
    Food(name:"Roasted Mighty Thistle", hearts: 0.5,
         ingredientNames: Ingredients(firstIngredient: "Mighty Thistle")),
    Food(name:"Roasted Porgy", hearts: 1.5,
         ingredientNames: Ingredients(firstIngredient: "Any Porgy")),
    Food(name:"Roasted Radish", hearts: 3.75,
         ingredientNames: Ingredients(firstIngredient: "Hearty Radish")),
    Food(name:"Roasted Swift Carrot", hearts: 0.75,
         ingredientNames: Ingredients(firstIngredient: "Swift Carrot")),
    Food(name:"Roasted Voltfruit", hearts: 0.75,
         ingredientNames: Ingredients(firstIngredient: "Voltfruit")),
    Food(name:"Roasted Wildberry", hearts: 0.75,
         ingredientNames: Ingredients(firstIngredient: "Wildberry")),
    Food(name:"Sneaky River Escargot", hearts: 1.5,
         ingredientNames: Ingredients(firstIngredient: "Sneaky River Snail")),
    Food(name:"Toasty Chillshroom", hearts: 0.75,
         ingredientNames: Ingredients(firstIngredient: "Chillshroom")),
    Food(name:"Toasty Endura Shroom", hearts: 1.5,
         ingredientNames: Ingredients(firstIngredient: "Endura Shroom")),
    Food(name:"Toasted Hearty Truffle", hearts: 3.0,
         ingredientNames: Ingredients(firstIngredient: "Hearty Truffle")),
    Food(name:"Toasted Big Hearty Truffle", hearts: 4.5,
         ingredientNames: Ingredients(firstIngredient: "Big Hearty Truffle")),
    Food(name:"Toasty Ironshroom", hearts: 0.75,
         ingredientNames: Ingredients(firstIngredient: "Ironshroom")),
    Food(name:"Toasty Hylian Shroom", hearts: 0.75,
         ingredientNames: Ingredients(firstIngredient: "Hylian Shroom")),
    Food(name:"Toasty Razorshroom", hearts: 0.75,
         ingredientNames: Ingredients(firstIngredient: "Razorshroom")),
    Food(name:"Toasty Rushroom", hearts: 0.75,
         ingredientNames: Ingredients(firstIngredient: "Rushroom")),
    Food(name:"Toasty Silent Shroom", hearts: 0.75,
         ingredientNames: Ingredients(firstIngredient: "Silent Shroom")),
    Food(name:"Toasty Stamella Shroom", hearts: 1.5,
         ingredientNames: Ingredients(firstIngredient: "Stamella Shroom")),
    Food(name:"Toasty Sunshroom", hearts: 0.75,
         ingredientNames: Ingredients(firstIngredient: "Sunshroom")),
    Food(name:"Toasty Zapfshroom", hearts: 0.75,
         ingredientNames: Ingredients(firstIngredient: "Zapfshroom")),
    Food(name:"Seared Steak", hearts: 1.5,
         ingredientNames: Ingredients(firstIngredient: "Raw Meat")),
    Food(name:"Seared Gourmet Steak", hearts: 4.5,
         ingredientNames: Ingredients(firstIngredient: "Raw Gourmet Meat")),
    Food(name:"Seared Prime Steak", hearts: 2.25,
         ingredientNames: Ingredients(firstIngredient: "Raw Prime Meat")),
    Food(name:"Roasted Bird Drumstick", hearts: 1.5,
         ingredientNames: Ingredients(firstIngredient: "Raw Bird Drumstick")),
    Food(name:"Roasted Whole Bird", hearts: 4.5,
         ingredientNames: Ingredients(firstIngredient: "Raw Whole Bird")),
    Food(name:"Roasted Bass", hearts: 1.5,
         ingredientNames: Ingredients(firstIngredient: "Hyrule Bass OR", secondIngredient: "Staminoka Bass")),
    Food(name:"Roasted Hearty Salmon", hearts: 4.5,
         ingredientNames: Ingredients(firstIngredient: "Hearty Salmon")),
    Food(name:"Roasted Trout", hearts: 1.5,
         ingredientNames: Ingredients(firstIngredient: "Any Trout")),
    Food(name:"Blackened Crab", hearts: 1.5,
         ingredientNames: Ingredients(firstIngredient: "Any Crab")),
    Food(name:"Roasted Tree Nut", hearts: 0.5,
         ingredientNames: Ingredients(firstIngredient: "Tree Nut")),
    Food(name:"Roasted Acorn", hearts: 0.5,
         ingredientNames: Ingredients(firstIngredient: "Acorn")),
    
    Food(name: "Frozen Bass", hearts: 2.0, effect: "Heat Resistance", duration: "1:00 min" ,
         ingredientNames: Ingredients(firstIngredient: "Any Bass")),
    Food(name: "Frozen Hearty Salmon", hearts: 4.0, effect: "Heat Resistance", duration: "1:00 min" ,
         ingredientNames: Ingredients(firstIngredient: "Hearty Salmon")),
    Food(name: "Frozen Bird Drumstick", hearts: 1.0, effect: "Heat Resistance", duration: "1:00 min" ,
         ingredientNames: Ingredients(firstIngredient: "Raw Bird Drumstick")),
    Food(name: "Frozen Bird Thigh", hearts: 1.0, effect: "Heat Resistance", duration: "1:00 min" ,
         ingredientNames: Ingredients(firstIngredient: "Raw Bird Thigh")),
    Food(name: "Frozen Whole Bird", hearts: 3.0, effect: "Heat Resistance", duration: "1:00 min" ,
         ingredientNames: Ingredients(firstIngredient: "Whole Bird")),
    Food(name: "Frozen Carp", hearts: 1.0, effect: "Heat Resistance", duration: "1:00 min" ,
         ingredientNames: Ingredients(firstIngredient: "Any Carp")),
    Food(name: "Frozen Hearty Bass", hearts: 2.0, effect: "Heat Resistance", duration: "1:00 min" ,
         ingredientNames: Ingredients(firstIngredient: "Any Bass")),
    Food(name: "Frozen Crab", hearts: 2.0, effect: "Heat Resistance", duration: "1:00 min" ,
         ingredientNames: Ingredients(firstIngredient: "Any Crab")),
    Food(name: "Frozen River Snail", hearts: 1.0, effect: "Heat Resistance", duration: "1:00 min" ,
         ingredientNames: Ingredients(firstIngredient: "Sneaky River Snail")),
    Food(name: "Frozen Trout", hearts: 1.0, effect: "Heat Resistance", duration: "1:00 min" ,
         ingredientNames: Ingredients(firstIngredient: "Any Trout")),
    Food(name: "Frozen River Snail", hearts: 1.0, effect: "Heat Resistance", duration: "1:00 min" ,
         ingredientNames: Ingredients(firstIngredient: "Sneaky River Snail")),
    Food(name: "Icy Hearty Blueshell Snail", hearts: 3.0, effect: "Heat Resistance", duration: "1:00 min" ,
         ingredientNames: Ingredients(firstIngredient: "Hearty Blueshell Snail")),
    Food(name: "Icy Meat", hearts: 1.0, effect: "Heat Resistance", duration: "1:00 min" ,
         ingredientNames: Ingredients(firstIngredient: "Raw Meat")),
    Food(name: "Icy Prime Meat", hearts: 1.5, effect: "Heat Resistance", duration: "1:00 min" ,
         ingredientNames: Ingredients(firstIngredient: "Raw Prime Meat")),
    Food(name: "Icy Gourmet Meat", hearts: 3.0, effect: "Heat Resistance", duration: "1:00 min" ,
         ingredientNames: Ingredients(firstIngredient: "Raw Gourmet Meat")),
   
    
]

let mealData = [
    
    Meal(name:"Spicy Sautéed Peppers",
         hearts: 1.5, duration: "2:30 min", effect: "Cold Resistance",
         ingredientNames: Ingredients(firstIngredient: "Spicy Pepper")),
    Meal(name:"Spicy Fish Skewer",
         hearts: 2.0, duration: "2:30 min", effect: "Cold Resistance",
         ingredientNames: Ingredients(firstIngredient: "Sizzlefin Trout")),
    Meal(name:"Chilly Simmered Fruit",
         hearts: 0.5, duration: "2:30 min", effect: "Heat Resistance",
         ingredientNames: Ingredients(firstIngredient: "Hydromelon")),
    Meal(name: "Hearty Salmon Meunière", hearts: 100.0,
         ingredientNames: Ingredients(firstIngredient: "Tabantha Wheat", secondIngredient: "Goat Butter", thirdIngredient: "Hearty Salmon"),
         heartsAdded: 4),
]

let elixirData = [
    Elixir(name:"Spicy Elixir", duration: "3:40 min", effect: "Cold Resistance",
           ingredientNames: Ingredients(firstIngredient: "Warm Darner", secondIngredient: "Bokoblin Horn")),
    Elixir(name:"Hasty Elixir", duration: "2:10 min", effect: "Speed Up",
           ingredientNames: Ingredients(firstIngredient: "Hot-Footed Frog", secondIngredient: "Bokoblin Horn")),
    Elixir(name:"Energizing Elixir", effect: "Restores Stamina",
           ingredientNames: Ingredients(firstIngredient: "Hot-Footed Frog", secondIngredient: "Bokoblin Horn"))
]

