//
//  SampleDate.swift
//  Link's Recipes
//
//  Created by Martin List on 14/03/2017.
//  Copyright © 2017 Martin List. All rights reserved.
//

import Foundation

let foodData = [
    Food(name:"Baked Apple", hearts: 0.75,
         ingredientNames: Ingredients(firstIngredient: "Apple")),
    Food(name:"Baked Palm Fruit", hearts: 1.5,
         ingredientNames: Ingredients(firstIngredient: "Palm Fruit")),
    Food(name:"Baked Fortified Pumpkin", hearts: 0.75,
         ingredientNames: Ingredients(firstIngredient: "Fortified Pumpkin")),
    Food(name:"Blueshell Escargot", hearts: 4.5,
         ingredientNames: Ingredients(firstIngredient: "Hearty Blueshell Snail")),
    Food(name:"Campfire Egg", hearts: 1.5,
         ingredientNames: Ingredients(firstIngredient: "Bird Egg")),
    Food(name:"Charred Pepper", hearts: 0.75,
         ingredientNames: Ingredients(firstIngredient: "Spicy Pepper")),
    Food(name:"Roasted Armoranth", hearts: 0.5,
         ingredientNames: Ingredients(firstIngredient: "Armoranth")),
    Food(name:"Roasted Hearty Bass", hearts: 3.0,
         ingredientNames: Ingredients(firstIngredient: "Hearty Bass")),
    Food(name:"Roasted Big Radish", hearts: 6.0,
         ingredientNames: Ingredients(firstIngredient: "Big Radish")),
    Food(name:"Roasted Bird Thigh", hearts: 2.25,
         ingredientNames: Ingredients(firstIngredient: "Raw Bird Thigh")),
    Food(name:"Roasted Carp", hearts: 1.5,
         ingredientNames: Ingredients(firstIngredient: "Any Carp")),
    Food(name:"Roasted Hearty Durian", hearts: 4.5,
         ingredientNames: Ingredients(firstIngredient: "Hearty Durian")),
    Food(name:"Roasted Endura Carrot", hearts: 3.0,
         ingredientNames: Ingredients(firstIngredient: "Endura Carrot")),
    Food(name:"Roasted Hydromelon", hearts: 0.75,
         ingredientNames: Ingredients(firstIngredient: "Hydromelon")),
    Food(name:"Roasted Lotus Seeds", hearts: 0.75,
         ingredientNames: Ingredients(firstIngredient: "Fleet-Lotus Seeds")),
    Food(name:"Roasted Mighty Bananas", hearts: 0.75,
         ingredientNames: Ingredients(firstIngredient: "Mighty Bananas")),
    Food(name:"Roasted Mighty Thistle", hearts: 0.5,
         ingredientNames: Ingredients(firstIngredient: "Mighty Thistle")),
    Food(name:"Roasted Porgy", hearts: 1.5,
         ingredientNames: Ingredients(firstIngredient: "Any Porgy")),
    Food(name:"Roasted Radish", hearts: 3.75,
         ingredientNames: Ingredients(firstIngredient: "Hearty Radish")),
    Food(name:"Roasted Swift Carrot", hearts: 0.75,
         ingredientNames: Ingredients(firstIngredient: "Swift Carrot")),
    Food(name:"Roasted Voltfruit", hearts: 0.75,
         ingredientNames: Ingredients(firstIngredient: "Voltfruit")),
    Food(name:"Roasted Wildberry", hearts: 0.75,
         ingredientNames: Ingredients(firstIngredient: "Wildberry")),
    Food(name:"Sneaky River Escargot", hearts: 1.5,
         ingredientNames: Ingredients(firstIngredient: "Sneaky River Snail")),
    Food(name:"Toasty Chillshroom", hearts: 0.75,
         ingredientNames: Ingredients(firstIngredient: "Chillshroom")),
    Food(name:"Toasty Endura Shroom", hearts: 1.5,
         ingredientNames: Ingredients(firstIngredient: "Endura Shroom")),
    Food(name:"Toasted Hearty Truffle", hearts: 3.0,
         ingredientNames: Ingredients(firstIngredient: "Hearty Truffle")),
    Food(name:"Toasted Big Hearty Truffle", hearts: 4.5,
         ingredientNames: Ingredients(firstIngredient: "Big Hearty Truffle")),
    Food(name:"Toasty Ironshroom", hearts: 0.75,
         ingredientNames: Ingredients(firstIngredient: "Ironshroom")),
    Food(name:"Toasty Hylian Shroom", hearts: 0.75,
         ingredientNames: Ingredients(firstIngredient: "Hylian Shroom")),
    Food(name:"Toasty Razorshroom", hearts: 0.75,
         ingredientNames: Ingredients(firstIngredient: "Razorshroom")),
    Food(name:"Toasty Rushroom", hearts: 0.75,
         ingredientNames: Ingredients(firstIngredient: "Rushroom")),
    Food(name:"Toasty Silent Shroom", hearts: 0.75,
         ingredientNames: Ingredients(firstIngredient: "Silent Shroom")),
    Food(name:"Toasty Stamella Shroom", hearts: 1.5,
         ingredientNames: Ingredients(firstIngredient: "Stamella Shroom")),
    Food(name:"Toasty Sunshroom", hearts: 0.75,
         ingredientNames: Ingredients(firstIngredient: "Sunshroom")),
    Food(name:"Toasty Zapfshroom", hearts: 0.75,
         ingredientNames: Ingredients(firstIngredient: "Zapfshroom")),
    Food(name:"Seared Steak", hearts: 1.5,
         ingredientNames: Ingredients(firstIngredient: "Raw Meat")),
    Food(name:"Seared Gourmet Steak", hearts: 4.5,
         ingredientNames: Ingredients(firstIngredient: "Raw Gourmet Meat")),
    Food(name:"Seared Prime Steak", hearts: 2.25,
         ingredientNames: Ingredients(firstIngredient: "Raw Prime Meat")),
    Food(name:"Roasted Bird Drumstick", hearts: 1.5,
         ingredientNames: Ingredients(firstIngredient: "Raw Bird Drumstick")),
    Food(name:"Roasted Whole Bird", hearts: 4.5,
         ingredientNames: Ingredients(firstIngredient: "Raw Whole Bird")),
    Food(name:"Roasted Bass", hearts: 1.5,
         ingredientNames: Ingredients(firstIngredient: "Hyrule Bass OR", secondIngredient: "Staminoka Bass")),
    Food(name:"Roasted Hearty Salmon", hearts: 4.5,
         ingredientNames: Ingredients(firstIngredient: "Hearty Salmon")),
    Food(name:"Roasted Trout", hearts: 1.5,
         ingredientNames: Ingredients(firstIngredient: "Any Trout")),
    Food(name:"Blackened Crab", hearts: 1.5,
         ingredientNames: Ingredients(firstIngredient: "Any Crab")),
    Food(name:"Roasted Tree Nut", hearts: 0.5,
         ingredientNames: Ingredients(firstIngredient: "Tree Nut")),
    Food(name:"Roasted Acorn", hearts: 0.5,
         ingredientNames: Ingredients(firstIngredient: "Acorn")),
    
    Food(name: "Frozen Bass", hearts: 2.0,
         ingredientNames: Ingredients(firstIngredient: "Any Bass"), firstEffect: Effect(effectName: "Heat Resistance", duration: "1:00 min", effectIngredient: "Any Bass")),
    Food(name: "Frozen Hearty Salmon", hearts: 4.0,
         ingredientNames: Ingredients(firstIngredient: "Hearty Salmon"),firstEffect: Effect(effectName: "Heat Resistance", duration: "1:00 min", effectIngredient: "Hearty Salmon")),
    Food(name: "Frozen Bird Drumstick", hearts: 1.0,
         ingredientNames: Ingredients(firstIngredient: "Raw Bird Drumstick"), firstEffect: Effect(effectName: "Heat Resistance", duration: "1:00 min", effectIngredient: "Bird Drumstick")),
    Food(name: "Frozen Bird Thigh", hearts: 1.0,
         ingredientNames: Ingredients(firstIngredient: "Raw Bird Thigh"), firstEffect: Effect(effectName: "Heat Resistance", duration: "1:00 min", effectIngredient: "Bird Thigh")),
    Food(name: "Frozen Whole Bird", hearts: 3.0,
         ingredientNames: Ingredients(firstIngredient: "Whole Bird"), firstEffect: Effect(effectName: "Heat Resistance", duration: "1:00 min", effectIngredient: "Whole Bird")),
    Food(name: "Frozen Carp", hearts: 1.0,
         ingredientNames: Ingredients(firstIngredient: "Any Carp"), firstEffect: Effect(effectName: "Heat Resistance", duration: "1:00 min", effectIngredient: "Any Carp")),
    Food(name: "Frozen Hearty Bass", hearts: 2.0,
         ingredientNames: Ingredients(firstIngredient: "Hearty Bass"), firstEffect: Effect(effectName: "Heat Resistance", duration: "1:00 min", effectIngredient: "Hearty Bass")),
    Food(name: "Frozen Crab", hearts: 2.0,
         ingredientNames: Ingredients(firstIngredient: "Any Crab"), firstEffect: Effect(effectName: "Heat Resistance", duration: "1:00 min", effectIngredient: "Any Crab")),
    Food(name: "Frozen River Snail", hearts: 1.0,
         ingredientNames: Ingredients(firstIngredient: "Sneaky River Snail"), firstEffect: Effect(effectName: "Heat Resistance", duration: "1:00 min", effectIngredient: "River Snail")),
    Food(name: "Frozen Trout", hearts: 1.0,
         ingredientNames: Ingredients(firstIngredient: "Any Trout"), firstEffect: Effect(effectName: "Heat Resistance", duration: "1:00 min", effectIngredient: "Any Trout")),
    Food(name: "Frozen Sneaky River Snail", hearts: 1.0,
         ingredientNames: Ingredients(firstIngredient: "Sneaky River Snail"), firstEffect: Effect(effectName: "Heat Resistance", duration: "1:00 min", effectIngredient: "Sneaky River Snail")),
    Food(name: "Icy Hearty Blueshell Snail", hearts: 3.0,
         ingredientNames: Ingredients(firstIngredient: "Hearty Blueshell Snail"), firstEffect: Effect(effectName: "Heat Resistance", duration: "1:00 min", effectIngredient: "Hearty Blueshell Snail")),
    Food(name: "Icy Meat", hearts: 1.0,
         ingredientNames: Ingredients(firstIngredient: "Raw Meat"), firstEffect: Effect(effectName: "Heat Resistance", duration: "1:00 min", effectIngredient: "Raw Meat")),
    Food(name: "Icy Prime Meat", hearts: 1.5,
         ingredientNames: Ingredients(firstIngredient: "Raw Prime Meat"), firstEffect: Effect(effectName: "Heat Resistance", duration: "1:00 min", effectIngredient: "Raw Prime Meat")),
    Food(name: "Icy Gourmet Meat", hearts: 3.0,
         ingredientNames: Ingredients(firstIngredient: "Raw Gourmet Meat"), firstEffect: Effect(effectName: "Heat Resistance", duration: "1:00 min", effectIngredient: "Raw Gourmet Meat")),
   
    
]

let mealData = [
    
    Meal(name:"Sautéed Peppers",
         hearts: 1.5, ingredientNames: Ingredients(firstIngredient: "Spicy Pepper"),
         firstEffect: Effect(effectName: "Cold Resistance", duration: "2:30 min", effectIngredient: "Spicy Pepper" )),
    Meal(name:"Fish Skewer",
         hearts: 2.0, ingredientNames: Ingredients(firstIngredient: "Sizzlefin Trout"),
         firstEffect: Effect(effectName: "Cold Resistance", duration: "2:30 min", effectIngredient: "Sizzlefin Trout" )),
    Meal(name:"Simmered Fruit",
         hearts: 0.5, ingredientNames: Ingredients(firstIngredient: "Hydromelon"),
         firstEffect: Effect(effectName: "Heat Resistance", duration: "2:30 min", effectIngredient: "Hydromelon" )),
    Meal(name: "Salmon Meunière", hearts: 100.0,
         ingredientNames: Ingredients(firstIngredient: "Tabantha Wheat", secondIngredient: "Goat Butter", thirdIngredient: "Hearty Salmon"),
         firstEffect: Effect(effectName: "Temporary Hearts", amount: 4.0, effectIngredient: "Hearty Salmon" )),
    Meal(name:"Apple Pie",
         hearts: 3.0,
         ingredientNames: Ingredients(firstIngredient: "Apple", secondIngredient: "Tabantha Wheat", thirdIngredient: "Cane Sugar", fourthIngredient: "Goat Butter")),
    Meal(name:"Carrot Cake", hearts: 3.0, ingredientNames: Ingredients(firstIngredient: "Any Carrot", secondIngredient: "Tabantha Wheat", thirdIngredient: "Cane Sugar", fourthIngredient: "Goat Butter"), firstEffect: Effect(effectName: "Overfills Stamina", amount: 0.4, effectIngredient: "Enduring Carrot" ),
         secondEffect: Effect(effectName: "Speed Up", duration: "3:20 min", effectIngredient: "Swift Carrot" )),
    Meal(name:"Veggie Cream Soup",
         hearts: 2.0,
         ingredientNames: Ingredients(firstIngredient: "Any Carrot", secondIngredient: "Fresh Milk", thirdIngredient: "Rock Salt"),
         firstEffect: Effect(effectName: "Speed Up", duration: "3:20 min", effectIngredient: "Swift Carrot" )),
    Meal(name:"Carrot Stew", hearts: 4.0, ingredientNames: Ingredients(firstIngredient: "Any Carrot", secondIngredient: "Tabantha Wheat", thirdIngredient: "Fresh Milk", fourthIngredient: "Goat Butter"), firstEffect: Effect(effectName: "Overfills Stamina", amount: 0.4, effectIngredient: "Enduring Carrot" ),
         secondEffect: Effect(effectName: "Speed Up", duration: "3:20 min", effectIngredient: "Swift Carrot" )),
    Meal(name:"Crab Omelet with Rice", hearts: 6.0, ingredientNames: Ingredients(firstIngredient: "Hylian Rice", secondIngredient: "Bird Egg", thirdIngredient: "Rock Salt", fourthIngredient: "Any Crab"), firstEffect: Effect(effectName: "Restores Stamina", amount: 0.2, effectIngredient: "Bright-Eyed Crab" ),
         secondEffect: Effect(effectName: "Defense Up", duration: "0:50 min", effectIngredient: "Ironshell Crab" ),
         thirdEffect: Effect(effectName: "Attack Up", duration: "0:50 min", effectIngredient: "Razorclaw Crab" )),
    Meal(name:"Crab Risotto", hearts: 4.0, ingredientNames: Ingredients(firstIngredient: "Hylian Rice", secondIngredient: "Goat Butter", thirdIngredient: "Rock Salt", fourthIngredient: "Any Crab"), firstEffect: Effect(effectName: "Restores Stamina", amount: 0.2, effectIngredient: "Bright-Eyed Crab" ),
         secondEffect: Effect(effectName: "Defense Up", duration: "0:50 min", effectIngredient: "Ironshell Crab" ),
         thirdEffect: Effect(effectName: "Attack Up", duration: "0:50 min", effectIngredient: "Razorclaw Crab")),
    Meal(name:"Crab Stir-Fry", hearts: 4.0, ingredientNames: Ingredients(firstIngredient: "Goron Spice", secondIngredient: "Any Crab"), firstEffect: Effect(effectName: "Restores Stamina", amount: 0.2, effectIngredient: "Bright-Eyed Crab" ),
         secondEffect: Effect(effectName: "Defense Up", duration: "2:20 min", effectIngredient: "Ironshell Crab" ),
         thirdEffect: Effect(effectName: "Attack Up", duration: "2:20 min", effectIngredient: "Razorclaw Crab")),
    Meal(name:"Cream of Mushroom Soup", hearts: 4.0, ingredientNames: Ingredients(firstIngredient: "Rock Salt", secondIngredient: "Fresh Milk", thirdIngredient: "Any Mushroom", fourthIngredient: "Any Herb"), firstEffect: Effect(effectName: "Restores Stamina", amount: 0.2, effectIngredient: "Bright-Eyed Crab" ),
         secondEffect: Effect(effectName: "Defense Up", duration: "0:50 min", effectIngredient: "Ironshell Crab" ),
         thirdEffect: Effect(effectName: "Attack Up", duration: "0:50 min", effectIngredient: "Razorclaw Crab")),

]

let elixirData = [
    Elixir(name:"Spicy Elixir", category: "Spicy", effect: "Cold Resistance"),
    Elixir(name:"Hasty Elixir", category: "Hasty", effect: "Speed Up"),
    Elixir(name:"Chilly Elixir", category: "Chilly", effect: "Heat Resistance"),
    Elixir(name:"Electro Elixir", category: "Electro", effect: "Electricity Resistance"),
    Elixir(name:"Enduring Elixir", category: "Enduring", effect: "Overfills Stamina"),
    Elixir(name:"Energizing Elixir", category: "Energizing", effect: "Restores Stamina"),
    Elixir(name:"Fireproof Elixir", category: "Fireproof", effect: "Fire Resistance"),
    Elixir(name:"Hearty Elixir", category: "Hearty", effect: "Temporary Hearts"),
    Elixir(name:"Sneaky Elixir", category: "Sneaky", effect: "Increased Stealth"),
    Elixir(name:"Tough Elixir", category: "Tough", effect: "Defense Up"),
    Elixir(name:"Mighty Elixir", category: "Mighty", effect: "Attack Up"),
]

let critterData = [
    Critter(name: "Hightail Lizard", category: "Hasty", effect: "Speed Up", duration: 60),
    Critter(name: "Hot-Footed Frog", category: "Hasty", effect: "Speed Up", duration: 60),
    
    Critter(name: "Warm Darner", category: "Spicy", effect: "Cold Resistance", duration: 150),
    Critter(name: "Summerwing Butterfly", category: "Spicy", effect: "Cold Resistance", duration: 150),
    
    
    Critter(name: "Tireless Frog", category: "Enduring", effect: "Overfills Stamina", amount: 0.2),

    Critter(name: "Thunderwing Butterfly", category: "Electro", effect: "Electricity Resistance", duration: 150),
    Critter(name: "Electric Darner", category: "Electro", effect: "Electricity Resistance", duration: 150),

    Critter(name: "Sunset Firefly", category: "Sneaky", effect: "Increased Stealth", duration: 120),
    
    Critter(name: "Smootherwing Butterfly", category: "Fireproof", effect: "Fire Resistance", duration: 150),
    Critter(name: "Fireproof Lizard", category: "Fireproof", effect: "Fire Resistance", duration: 150),
    
    Critter(name: "Rugged Rhino Beetle", category: "Tough", effect: "Defense Up", duration: 50),
    
    Critter(name: "Cold Darner", category: "Chilly", effect: "Heat Resistance", duration: 150),
    Critter(name: "Winterwing Butterfly", category: "Chilly", effect: "Heat Resistance", duration: 150),
    
    Critter(name: "Hearty Lizard", category: "Hearty", effect: "Temporary Hearts", amount: 0.2),
    
    Critter(name: "Restless Cricket", category: "Energizing", effect: "Restores Stamina", amount: 0.2),
    Critter(name: "Energetic Rhino Beetle", category: "Energizing", effect: "Restores Stamina", amount: 1.6),
    
    Critter(name: "Bladed Rhino Beetle", category: "Mighty", effect: "Attack Up", duration: 50),

]

let monsterPartData = [
    MonsterPart(name: "Bokoblin Fang", duration: 110),
    MonsterPart(name: "Bokoblin Horn", duration: 70),
    MonsterPart(name: "Chuchu Jelly", duration: 70),
    MonsterPart(name: "Electric Keese Wing", duration: 110),
    MonsterPart(name: "Keese Eyeball", duration: 190),
    MonsterPart(name: "Keese Wing", duration: 70),
    MonsterPart(name: "Lizalfos Horn", duration: 70),
    MonsterPart(name: "Lizalfos Tail", duration: 190),
    MonsterPart(name: "Lizalfos Talon", duration: 110),
    MonsterPart(name: "Moblin Fang", duration: 110),
    MonsterPart(name: "Moblin Horn", duration: 70),
    MonsterPart(name: "Octorok Balloon", duration: 70),
    MonsterPart(name: "Octorok Eyeball", duration: 110),
    MonsterPart(name: "Octorok Tentacle", duration: 70),
    MonsterPart(name: "Red Chuchu Jelly", duration: 110),
    MonsterPart(name: "White Chuchu Jelly", duration: 110),
]
